#!/bin/bash
#SBATCH --partition=A40devel
#SBATCH --nodes=1
#SBATCH --tasks-per-node=1
#SBATCH --job-name=test
#SBATCH --output=outputs/donuttest-%j.out
#SBATCH --error=outputs/donuttest-%j.err
#SBATCH --gres gpu:1
#SBATCH --cpus-per-task=1
#SBATCH --time=1:00:00
#SBATCH --mem=10gb
source /home/s6anthel/.bashrc
conda activate donuttest
python -m src.historicdocumentprocessing.testdonut