#!/bin/bash
#SBATCH --partition=A40short
#SBATCH --nodes=1
#SBATCH --tasks-per-node=1
#SBATCH --job-name=postprocess
#SBATCH --output=outputs/rcnn_find_filterpoint-%j.out
#SBATCH --error=outputs/rcnn_find_filterpoint-%j.err
#SBATCH --gres gpu:1
#SBATCH --cpus-per-task=1
#SBATCH --time=8:00:00
#SBATCH --mem=10gb
source /home/s6anthel/.bashrc
module load CUDA
conda activate kosmos2

python -m src.historicdocumentprocessing.util.metricsutil