#!/bin/bash
#SBATCH --partition=A40medium
#SBATCH --nodes=1
#SBATCH --tasks-per-node=1
#SBATCH --job-name=postprocess
#SBATCH --output=outputs/postprocess%j.out
#SBATCH --error=outputs/postprocess%j.err
#SBATCH --gres gpu:1
#SBATCH --cpus-per-task=1
#SBATCH --time=24:00:00
#SBATCH --mem=10gb
source /home/s6anthel/.bashrc
module load CUDA
conda activate newkosmos2

python -m src.historicdocumentprocessing.postprocessing