#!/bin/bash
#SBATCH --partition=A100medium
#SBATCH --nodes=1
#SBATCH --tasks-per-node=1
#SBATCH --job-name=test
#SBATCH --output=outputs/rcnn-wild-train-test-%j.out
#SBATCH --error=outputs/rcnn-wild-train-test_%j.err
#SBATCH --gres gpu:1
#SBATCH --cpus-per-task=1
#SBATCH --time=24:00:00
#SBATCH --mem=10gb
source /home/s6anthel/.bashrc
module load CUDA
conda activate kosmos2

epoch=$1
startepoch=$2
model=$3
randominit=$4

echo "$epoch"
echo "$startepoch"
echo "$model"

if [ "$randominit" = true ]
then
  python -m src.historicdocumentprocessing.fasterrcnn_trainer --name "testseveralcalls_no_valid_random_init_e_250" --epochs "$epoch" --startepoch "$startepoch" --randominit --no-valid --identicalname
else
  python -m src.historicdocumentprocessing.fasterrcnn_trainer --name "testseveralcalls_no_valid_random_init_e_250" --epochs "$epoch" --startepoch "$startepoch" --load "$model" --no-valid --identicalname
fi