#!/bin/bash
#SBATCH --partition=A100short
#SBATCH --nodes=1
#SBATCH --tasks-per-node=1
#SBATCH --job-name=train
#SBATCH --output=outputs/tabletransformer-bonntrain-%j.out
#SBATCH --error=outputs/tabletransformer-bonntrain%j.err
#SBATCH --gres gpu:1
#SBATCH --cpus-per-task=1
#SBATCH --time=8:00:00
#SBATCH --mem=10gb
source /home/s6anthel/.bashrc
module load CUDA
conda activate kosmos2

python -m src.historicdocumentprocessing.tabletransformer_train --name "BonnDataFullImage_tabletransformer_v1.1" --dataset "BonnData" --valid --no-early_stopping
