#!/bin/bash
#SBATCH --partition=A40medium
#SBATCH --nodes=1
#SBATCH --tasks-per-node=1
#SBATCH --job-name=train
#SBATCH --output=outputs/tabletransformer-titw-%j.out
#SBATCH --error=outputs/tabletransformer-titw%j.err
#SBATCH --gres gpu:1
#SBATCH --cpus-per-task=1
#SBATCH --time=24:00:00
#SBATCH --mem=10gb
source /home/s6anthel/.bashrc
module load CUDA
conda activate newkosmos2

epoch=$1
model=$2

echo "$epoch"
echo "$model"

python -m src.historicdocumentprocessing.tabletransformer_train --name "titw_severalcalls_2_e250" --dataset "Tablesinthewild" --valid --no-early_stopping --epochs "$epoch" --load "$model" --identicalname