#!/bin/bash
#SBATCH --partition=A40medium
#SBATCH --nodes=1
#SBATCH --tasks-per-node=1
#SBATCH --job-name=train
#SBATCH --output=outputs/tabletransformer-bonntrain-%j.out
#SBATCH --error=outputs/tabletransformer-bonntrain%j.err
#SBATCH --gres gpu:1
#SBATCH --cpus-per-task=1
#SBATCH --time=24:00:00
#SBATCH --mem=10gb
source /home/s6anthel/.bashrc
module load CUDA
conda activate newkosmos2

python -m src.historicdocumentprocessing.tabletransformer_train --name "titw_test" --dataset "Tablesinthewild" --valid --no-early_stopping